pagingNSortingInMVC4/Controllers/GameController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace pagingNSortingInMVC4.Controllers
{
    public class GameController : Controller
    {
        //
        // GET: /Game/

        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Hallown()
        {

            return View();
        }

        public JsonResult MatchPair(string matchcount)
         {
             JsonResult json = new JsonResult();
             json.Data = matchcount;
            // insert attempt count
            // Fetch counter with database for no.of attempt he played game
            // 
             return json;
        }

    }
}

pagingNSortingInMVC4/Views/Game/Hallown.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">

    <title>Halloween Memory Game!</title>

    <
    <link href="~/Content/css/style.css" rel="stylesheet" />

    <script src="~/Content/js/prefixfree.min.js"></script>
    <script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>

    <script src="~/Content/js/game.js"></script>


    <script src="~/Scripts/Timer/jquery.countdown360.min.js"></script>

</head>

<body>
    <input type="hidden" id="hdnmoves" />

    <div id="gameBoard">
        <span id="gameButtons">
            <span class="button">
                <span id="counter">0</span> Moves
            </span>

            <span class="button">
                <a id="strt_btn" onclick="startAgain();">@*Start again*@</a>
            </span>

        </span>

        <div id="boxes"> </div>
    </div>
    <span id="countdown">

    </span>

</body>

</html>

<script type="text/javascript">


    function funshowalert() {
        setTimeout(function () {
        }, startTimer());
    }

    $(document).on("ready", function () {
        setTimeout(function () {
        }, startTimer());
    });


    function funalert() {
        alert("Time Up");
        var matchcount = $("#hdnmoves").val();
        // alert($("#hdnmoves").val());
        //$("#strt_btn").click();
        //initializeTimer();
        //startTimer();

        $.post("@Url.Action("MatchPair","Game")", { matchcount: matchcount })
  .done(function (data) {
      alert("You had matches: " + data+" pairs");
  });
    }

    var countdown;
    function initializeTimer() {
        //Initialization
        countdown = $("#countdown").countdown360({
            radius: 60,
            seconds: 15,
            label: ['sec', 'secs'],
            fontColor: '#FFFFFF',
            autostart: false,
            onComplete: function () {

                funalert();

                //initializeTimer();
                //startTimer();
            }
        });

        //Call this, otherwise widget does not show up on the screen. Stop immediately after.
        countdown.start();
        countdown.stop();
    }

    initializeTimer();

    function startTimer() {
        countdown.start();
    }

    $('#countdown').click(function () {
        countdown.extendTimer(2);
    });


</script>



pagingNSortingInMVC4/Views/Game/Index.cshtml
@{
    ViewBag.Title = "Index";
}
<link href="~/Content/blockrain.css" rel="stylesheet" />
<script src="~/Scripts/blockrain.jquery.js"></script>
<script src="~/Scripts/blockrain.jquery.min.js"></script>
<h2>Index</h2>